// YouTube transcript parsing (docs/plan.md "Phase 2: T10 YouTube
// transcripts"). Pure functions over DOM subtrees and caption payloads, so
// they are unit-testable against saved fixtures (youtube.test.ts). The
// acquisition side (opening the transcript panel, finding the caption track
// the player already loaded) lives in ./acquire.ts.
//
// Two sources, both already on the page:
//  - the transcript panel ("Show transcript"): segments with an "m:ss"
//    timestamp. 2026 markup is `transcript-segment-view-model`; the older
//    `ytd-transcript-segment-renderer` is still handled.
//  - the caption track the player fetched (/api/timedtext): json3 (events
//    with tStartMs/dDurationMs/segs), or the XML formats (srv1 <text
//    start dur>, srv3 <p t d>).

/** One caption/transcript line. Times in seconds. */
export interface Cue {
  start: number;
  /** Duration, when the source gives one (caption tracks do; the panel doesn't). */
  dur?: number;
  text: string;
}

export type TranscriptSource = "panel" | "captions" | "track" | "text";

export interface Transcript {
  videoId: string;
  cues: Cue[];
  source: TranscriptSource;
  /** BCP-47-ish language code when known (caption track, or the page's track list). */
  language?: string;
  /** True for YouTube's automatic (ASR) captions, when known. */
  autoGenerated?: boolean;
}

/** "1:02:03" / "12:34" / "0:07" -> seconds; null when it isn't a timestamp. */
export function parseTimestamp(s: string): number | null {
  const m = s.trim().match(/^(?:(\d+):)?(\d{1,2}):(\d{2})$/);
  if (!m) return null;
  const h = m[1] ? Number(m[1]) : 0;
  const min = Number(m[2]);
  const sec = Number(m[3]);
  if (sec >= 60 || (m[1] !== undefined && min >= 60)) return null;
  return h * 3600 + min * 60 + sec;
}

/** Seconds -> "m:ss" or "h:mm:ss", like YouTube's own labels. */
export function formatTimestamp(totalSeconds: number): string {
  const t = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(t / 3600);
  const m = Math.floor((t % 3600) / 60);
  const s = t % 60;
  const ss = String(s).padStart(2, "0");
  return h > 0 ? `${h}:${String(m).padStart(2, "0")}:${ss}` : `${m}:${ss}`;
}

// Sound tags and speaker markers carry no authorship signal: "[Music]",
// "(applause)", "♪ ... ♪", ">> ", "- ". Keeps ordinary parentheses in speech.
const SOUND_TAG = /\[[^\]]{0,40}\]|\((?:music|applause|laughter|laughs|inaudible|silence|cheering|sighs?)\)|[♪♫]+/gi;

export function cleanCueText(text: string): string {
  return text
    .replace(/​/g, "")
    .replace(SOUND_TAG, " ")
    .replace(/(^|\s)>>+\s*/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function finalize(cues: Cue[]): Cue[] {
  const out: Cue[] = [];
  for (const c of cues) {
    const text = cleanCueText(c.text);
    if (!text || !Number.isFinite(c.start)) continue;
    out.push(c.dur !== undefined && Number.isFinite(c.dur) ? { start: c.start, dur: c.dur, text } : { start: c.start, text });
  }
  out.sort((a, b) => a.start - b.start);
  return out;
}

const PANEL_SEGMENT = "transcript-segment-view-model, ytd-transcript-segment-renderer";

/** Transcript panel segments under `root` (a panel, or the whole document). */
export function parsePanelSegments(root: ParentNode): Cue[] {
  const cues: Cue[] = [];
  for (const seg of Array.from(root.querySelectorAll(PANEL_SEGMENT))) {
    let stamp: string | null = null;
    let text: string | null = null;
    if (seg.tagName.toLowerCase() === "transcript-segment-view-model") {
      stamp = seg.querySelector('[class*="SegmentViewModelTimestamp"]:not([class*="A11y"])')?.textContent ?? null;
      text = seg.querySelector('span[role="text"], [class*="AttributedString"]')?.textContent ?? null;
    } else {
      stamp = seg.querySelector(".segment-timestamp")?.textContent ?? null;
      text = seg.querySelector(".segment-text, yt-formatted-string")?.textContent ?? null;
    }
    const start = stamp !== null ? parseTimestamp(stamp) : null;
    if (start === null || text === null) continue;
    cues.push({ start, text });
  }
  return finalize(cues);
}

interface Json3 {
  events?: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string }>; aAppend?: number }>;
}

/** YouTube json3 caption payload (`fmt=json3`). Append-only events (ASR line joins) are skipped. */
export function parseJson3(data: unknown): Cue[] {
  const events = (data as Json3 | null)?.events;
  if (!Array.isArray(events)) return [];
  const cues: Cue[] = [];
  for (const e of events) {
    if (!e?.segs || e.aAppend) continue;
    const text = e.segs.map((s) => s?.utf8 ?? "").join("");
    if (!text.trim()) continue;
    cues.push({ start: (e.tStartMs ?? 0) / 1000, dur: e.dDurationMs !== undefined ? e.dDurationMs / 1000 : undefined, text });
  }
  return finalize(cues);
}

function decodeEntities(s: string): string {
  return s
    .replace(/<[^>]+>/g, "")
    .replace(/&#(\d+);/g, (_, n: string) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n: string) => String.fromCodePoint(parseInt(n, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;|&#39;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

/** Timed-text XML: srv1 `<text start="1.2" dur="3">` (seconds) or srv3 `<p t="1200" d="3000">` (ms). */
export function parseTimedTextXml(xml: string): Cue[] {
  const cues: Cue[] = [];
  const srv1 = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  const srv3 = /<p\b([^>]*)>([\s\S]*?)<\/p>/g;
  const attr = (attrs: string, name: string) => attrs.match(new RegExp(`\\b${name}="([^"]*)"`))?.[1];
  let m: RegExpExecArray | null;
  while ((m = srv1.exec(xml))) {
    const start = Number(attr(m[1]!, "start"));
    const dur = attr(m[1]!, "dur");
    cues.push({ start, dur: dur !== undefined ? Number(dur) : undefined, text: decodeEntities(decodeEntities(m[2]!)) });
  }
  if (cues.length === 0) {
    while ((m = srv3.exec(xml))) {
      const t = Number(attr(m[1]!, "t"));
      const d = attr(m[1]!, "d");
      cues.push({ start: t / 1000, dur: d !== undefined ? Number(d) / 1000 : undefined, text: decodeEntities(m[2]!) });
    }
  }
  return finalize(cues);
}

/** Parses a /api/timedtext response body in whichever format it came in. */
export function parseCaptionPayload(body: string): Cue[] {
  const trimmed = body.trim();
  if (!trimmed) return [];
  if (trimmed.startsWith("{")) {
    try {
      return parseJson3(JSON.parse(trimmed));
    } catch {
      return [];
    }
  }
  if (trimmed.startsWith("<")) return parseTimedTextXml(trimmed);
  return [];
}

/**
 * True when the cues read like classic YouTube auto-captions: almost no
 * sentence punctuation and no capitalisation. (2026 ASR tracks are often
 * punctuated; uploaded captions nearly always are.)
 */
export function looksUnpunctuated(cues: readonly Cue[]): boolean {
  let words = 0;
  let marks = 0;
  let caps = 0;
  for (const c of cues) {
    for (const w of c.text.split(/\s+/)) {
      if (!w) continue;
      words++;
      if (/[.?!,;:]$/.test(w)) marks++;
      if (/^[A-Z][a-z]/.test(w) && w !== "I" && !w.startsWith("I'")) caps++;
    }
  }
  if (words < 20) return false;
  return marks / words < 0.02 && caps / words < 0.02;
}

// Top English function words: a transcript this short of them isn't English.
const EN_STOP = new Set(
  "the a an and or but of to in on at for with is are was were be been it that this you i we they he she not have has do so what if as from".split(" "),
);

/** Cheap English check (the detectors and the calibration are English-only). */
export function looksEnglish(text: string): boolean {
  const words = text.toLowerCase().match(/[a-z']+|[^\s\x00-\x7f]+/g) ?? [];
  if (words.length < 20) return true;
  let hits = 0;
  for (const w of words) if (EN_STOP.has(w)) hits++;
  return hits / words.length >= 0.12;
}

const TS = String.raw`(?:(\d{1,2}):)?(\d{1,2}):(\d{2})(?:[.,](\d{1,3}))?`;
const ARROW_LINE = new RegExp(String.raw`^\s*${TS}\s*-->\s*${TS}`);
const STAMP_PREFIX = new RegExp(String.raw`^\s*[\[(]?${TS}[\])]?\s+(.*\S)\s*$`);

function tsSeconds(m: RegExpMatchArray, at: number): number {
  const h = m[at] ? Number(m[at]) : 0;
  const frac = m[at + 3] ? Number(`0.${m[at + 3]}`) : 0;
  return h * 3600 + Number(m[at + 1]) * 60 + Number(m[at + 2]) + frac;
}

/**
 * Subtitle / transcript text as shown on a page: SRT, WebVTT, or
 * "0:12 some words" transcript lines. Styling tags, cue numbers and VTT
 * headers/notes are dropped. Pure.
 */
export function parseSubtitleText(text: string): Cue[] {
  const lines = text.replace(/\r/g, "").split("\n");
  const cues: Cue[] = [];
  let cur: { start: number; dur?: number; text: string[] } | null = null;
  const flush = () => {
    if (cur && cur.text.length) cues.push({ start: cur.start, dur: cur.dur, text: cur.text.join(" ") });
    cur = null;
  };
  let arrows = 0;
  for (const line of lines) {
    const a = line.match(ARROW_LINE);
    if (a) {
      flush();
      arrows++;
      const start = tsSeconds(a, 1);
      cur = { start, dur: Math.max(0, tsSeconds(a, 5) - start), text: [] };
      continue;
    }
    if (arrows > 0) {
      if (!line.trim()) flush();
      else if (cur && !/^\d+$/.test(line.trim())) cur.text.push(line.replace(/<[^>]+>/g, "").replace(/\{[^}]*\}/g, "").trim());
    }
  }
  flush();
  if (arrows > 0) return finalize(cues);
  // No SRT/VTT arrows: "0:12 text" transcript lines.
  for (const line of lines) {
    const m = line.match(STAMP_PREFIX);
    if (m) cues.push({ start: tsSeconds(m, 1), text: m[5]! });
  }
  return finalize(cues);
}
