// GENERATED by scripts/eval/fit-display.mjs from the T7 browser calibration
// run (docs/calibration.md, "Display probability"). Do not edit by hand.
// Piecewise-linear isotonic curves: engine score -> P(AI) on web text.

export interface DisplayCurve {
  x: number[];
  y: number[];
}

export const DISPLAY_FIT = {
  filterThreshold: 0.7,
  minWordsForScore: 30,
  shortTextWords: 150,
  defaultProfile: "modernbert+perplexity+tmr|weighted",
};

export const DISPLAY_CURVES: Record<string, DisplayCurve> = {
  "pooled|webgpu|long": { x: [0, 0.5, 1], y: [0.05, 0.6, 0.97] },
  "pooled|webgpu|short": { x: [0, 0.5, 1], y: [0.1, 0.55, 0.9] },
  "pooled|wasm|long": { x: [0, 0.5, 1], y: [0.05, 0.6, 0.97] },
  "pooled|wasm|short": { x: [0, 0.5, 1], y: [0.1, 0.55, 0.9] },
};
