// T10 YouTube transcripts: the report the content script keeps for the
// current video (read by the side panel via `getTranscriptReport`), and the
// transcript display mapping (engine score -> shown %), fitted separately
// from web text because captions read differently (docs/calibration.md
// "Transcripts"). Additive; nothing else in the shared contract changes.

import { MIN_WORDS_FOR_SCORE, SHORT_TEXT_WORDS } from "./thresholds";
import { TRANSCRIPT_CURVES } from "./transcriptCalibration";
import type { Tier } from "./settings";

export type TranscriptState =
  /** Not checked yet (reading it needs the panel opened: click to check). */
  | "idle"
  | "running"
  | "done"
  /** The video has no captions or transcript. */
  | "none"
  /** Captions exist but aren't English (the detectors and calibration are English-only). */
  | "not-english"
  /** Got the transcript, but scoring it needs the model download consented to first. */
  | "consent"
  /** Couldn't read the transcript. */
  | "error";

export interface TranscriptSegment {
  /** Seconds. */
  start: number;
  end: number;
  /** Engine score (0..1, same scale as `SentenceScore.score`). */
  score: number;
  /** Transcript-calibrated P(AI); undefined below MIN_WORDS_FOR_SCORE words. */
  probability?: number;
  words: number;
  /** First words of the segment, for the list. */
  snippet: string;
}

export interface TranscriptReport {
  videoId: string;
  state: TranscriptState;
  /** "fast" = the automatic pass, "full" = the clicked run (whole transcript, all detectors). */
  pass?: "fast" | "full";
  /**
   * Same pass, as the tiers task's `Tier` ("fast" -> "quick", "full" ->
   * "deep"): a voice check (T11, once it has its own rate setting) can read
   * this to pick Light (quick) vs Thorough (deep) -- docs/plan.md "Two
   * tiers".
   */
  tier?: Tier;
  /** Transcript-calibrated P(AI) for the whole transcript; undefined = "—". */
  probability?: number;
  overall?: number;
  source?: "panel" | "captions";
  autoGenerated?: boolean;
  language?: string;
  /** Words analysed / words in the transcript (long videos are sampled evenly). */
  analysedWords?: number;
  totalWords?: number;
  /** Seconds covered by the transcript. */
  duration?: number;
  segments: TranscriptSegment[];
  /** YouTube's own disclosure label ("Made with AI", "Altered or synthetic content"), if shown. */
  disclosure: string | null;
  error?: string;
  /** state "consent": the one-off download size the background quoted (undefined = unknown). */
  consentMB?: number;
}

export interface TranscriptDisplayContext {
  detectors?: readonly string[];
  method?: string;
  words?: number;
}

const DEFAULT_PROFILE = "fakespot+tmr|weighted";

function interp(xs: number[], ys: number[], x: number): number {
  if (x <= xs[0]!) return ys[0]!;
  for (let i = 1; i < xs.length; i++) {
    if (x <= xs[i]!) {
      const t = (x - xs[i - 1]!) / (xs[i]! - xs[i - 1]! || 1);
      return ys[i - 1]! + t * (ys[i]! - ys[i - 1]!);
    }
  }
  return ys[ys.length - 1]!;
}

/**
 * Engine score -> P(AI) for a YouTube transcript (50/50 prior), from the
 * transcript eval set. Detector sets without a transcript curve use the
 * default Fusion one. Undefined below MIN_WORDS_FOR_SCORE words.
 */
export function toTranscriptProbability(score: number, ctx: TranscriptDisplayContext = {}): number | undefined {
  if (!Number.isFinite(score)) return undefined;
  if (ctx.words !== undefined && ctx.words < MIN_WORDS_FOR_SCORE) return undefined;
  const dets = ctx.detectors?.length ? [...ctx.detectors].sort().join("+") : null;
  const key = !dets ? DEFAULT_PROFILE : ctx.detectors!.length === 1 ? dets : `${dets}|${ctx.method ?? "weighted"}`;
  const len = (ctx.words ?? SHORT_TEXT_WORDS) < SHORT_TEXT_WORDS ? "short" : "long";
  const c = TRANSCRIPT_CURVES[`${key}|${len}`] ?? TRANSCRIPT_CURVES[`${DEFAULT_PROFILE}|${len}`];
  if (!c) return undefined;
  return Math.min(0.99, Math.max(0.01, interp(c.x, c.y, score)));
}
