// GENERATED by scripts/eval/transcripts/fit-transcripts.mjs from the T10 transcript eval set
// (docs/calibration.md, "Transcripts"). Do not edit by hand.
// Piecewise-linear isotonic curves: engine score -> P(AI) for a YouTube
// transcript with a 50/50 human/AI mix, per detector set | length.

export const TRANSCRIPT_CURVES: Record<string, { x: number[]; y: number[] }> = {
  "fakespot+tmr|weighted|long": { x: [0,0.0029,0.0139,0.0288,0.0624,0.1225,0.2356,0.3574,0.4635,0.728,1], y: [0.2281,0.2281,0.2281,0.2705,0.2705,0.348,0.5476,0.7447,0.8471,0.97,0.97] },
  "fakespot+tmr|weighted|short": { x: [0,0.0016,0.032,0.0713,0.0881,0.147,0.2827,0.4764,0.6587,0.8098,0.8964,1], y: [0.2423,0.2423,0.2423,0.2423,0.3964,0.4893,0.5679,0.7817,0.8847,0.97,0.97,0.97] },
  "lite|long": { x: [0,0.0022,0.0053,0.0291,0.1427,0.5702,1], y: [0.3578,0.4536,0.5881,0.6918,0.8076,0.9576,0.9576] },
  "lite|short": { x: [0,0.0002,0.0012,0.0056,0.0289,0.1191,0.5385,1], y: [0.1615,0.4834,0.6541,0.7532,0.8353,0.8537,0.9206,0.9206] },
};
