// GENERATED by scripts/eval/transcripts/fit-transcripts.mjs from the T10 transcript eval set
// (docs/calibration.md, "Transcripts"). Do not edit by hand.
// Piecewise-linear isotonic curves: engine score -> P(AI) for a YouTube
// transcript with a 50/50 human/AI mix, per detector set | length.

export const TRANSCRIPT_CURVES: Record<string, { x: number[]; y: number[] }> = {
  "fakespot+tmr|weighted|long": { x: [0,0.0104,0.025,0.1283,0.2707,0.3615,0.659,1], y: [0.0572,0.0572,0.1854,0.224,0.4443,0.6732,0.97,0.97] },
  "fakespot+tmr|weighted|short": { x: [0,0.0031,0.0119,0.0514,0.2508,0.5686,0.8296,1], y: [0.1779,0.1779,0.1779,0.2004,0.3549,0.8167,0.97,0.97] },
  "lite|long": { x: [0,0.0001,0.0022,0.0054,0.0294,0.1122,0.1997,0.5712,1], y: [0.1496,0.3898,0.3898,0.4384,0.5133,0.7046,0.7046,0.9373,0.9373] },
  "lite|short": { x: [0,0.0001,0.0006,0.0015,0.0056,0.0209,0.1111,0.2917,0.4291,0.7482,1], y: [0.0858,0.1623,0.361,0.5379,0.5916,0.6928,0.8165,0.8165,0.8165,0.9174,0.9174] },
  "tmr|long": { x: [0,0.0313,0.1008,0.1446,0.2806,0.5629,1], y: [0.2303,0.2989,0.4367,0.6398,0.8298,0.9302,0.9302] },
  "tmr|short": { x: [0,0.0002,0.0372,0.1355,0.2616,0.358,0.5753,1], y: [0.2081,0.3232,0.3232,0.4924,0.5771,0.6009,0.97,0.97] },
};
