// Media pages that aren't YouTube (the page router, src/content/main.ts):
//
//  - "video": the page's main <video>. Its transcript comes from a
//    <track kind=captions|subtitles> if it has one (loaded with the track
//    hidden, so nothing shows), scored like a YouTube transcript; the voice
//    check is offered on click only.
//  - "subtitles": a raw .srt/.vtt file or a transcript page. The page's own
//    text is parsed into timed cues and scored transcript-style, with
//    timestamps on the flagged segments.

import type { Acquired } from "./youtube/acquire";
import { looksUnpunctuated, parseSubtitleText, type Cue } from "./youtube/transcript";
import { startPageTranscript, stopPageTranscript } from "./youtube";
import { offerVoiceOnClick, withdrawVoiceOffer } from "../voice/content";
import { dominantPlayer } from "./pageType";

/** The page's largest <video>, if any. */
export function mainVideo(doc: Document): HTMLVideoElement | null {
  const p = dominantPlayer(doc, { width: innerWidth, height: innerHeight });
  if (p.el instanceof HTMLVideoElement) return p.el;
  return doc.querySelector("video");
}

function pickTextTrack(video: HTMLVideoElement): TextTrack | null {
  const tracks = Array.from(video.textTracks ?? []).filter((t) => t.kind === "captions" || t.kind === "subtitles");
  return tracks.find((t) => /^en\b/i.test(t.language)) ?? tracks.find((t) => t.mode === "showing") ?? tracks[0] ?? null;
}

/** Reads a <track>'s cues without showing them (mode "hidden" loads it), then restores its mode. */
export async function readTrackCues(video: HTMLVideoElement, timeoutMs = 4000): Promise<{ cues: Cue[]; language?: string } | null> {
  const track = pickTextTrack(video);
  if (!track) return null;
  const mode = track.mode;
  if (mode === "disabled") track.mode = "hidden";
  try {
    const t0 = Date.now();
    while (!track.cues?.length && Date.now() - t0 < timeoutMs) await new Promise((r) => setTimeout(r, 200));
    const cues: Cue[] = Array.from(track.cues ?? []).map((c) => {
      const vc = c as VTTCue;
      return { start: vc.startTime, dur: vc.endTime - vc.startTime, text: (vc.text ?? "").replace(/<[^>]+>/g, " ") };
    });
    return { cues: cues.filter((c) => c.text.trim()), language: track.language || undefined };
  } finally {
    if (mode === "disabled") track.mode = "disabled";
  }
}

function toAcquired(id: string, cues: Cue[], source: "track" | "text", language?: string): Acquired {
  if (cues.length === 0) return { status: "none" };
  return { status: "ok", transcript: { videoId: id, cues, source, language, autoGenerated: looksUnpunctuated(cues) } };
}

/** Starts the video-page pipeline: transcript from <track> (if any), voice on click. */
export function startVideoPage(doc: Document): void {
  const video = mainVideo(doc);
  if (!video) return;
  offerVoiceOnClick(video);
  const hasTrack = !!video.querySelector("track") || (video.textTracks?.length ?? 0) > 0;
  if (!hasTrack) return;
  const id = `page:${location.pathname}`;
  void startPageTranscript(id, async () => {
    const got = await readTrackCues(video);
    return got ? toAcquired(id, got.cues, "track", got.language) : { status: "none" };
  });
}

/** Starts the subtitles pipeline: the page's own text, as timed cues. */
export function startSubtitlesPage(doc: Document): void {
  const id = `text:${location.pathname}`;
  void startPageTranscript(id, async () => toAcquired(id, parseSubtitleText(doc.body?.innerText || doc.body?.textContent || ""), "text"));
}

export function stopPageMedia(): void {
  stopPageTranscript();
  withdrawVoiceOffer();
}
