// Result model for image/text provenance checks (T4). Shared by the
// provenance host (Chrome offscreen doc / Firefox event page), the background
// router, the content script (badges) and the popup/options UI.
//
// Honesty rules (docs/watermarks.md "UI honesty"):
//  - Metadata (IPTC/XMP/PNG text/EXIF) is an *unsigned claim*: signed=false,
//    trusted=false, always.
//  - A C2PA manifest is signed; it is `trusted` only if its signer chains to
//    the bundled C2PA Trust List and the manifest validated.
//  - An open-source invisible watermark hit is a positive; a miss means
//    nothing (the watermark is fragile), so misses are never signals.
//  - "No signals found" never means "human-made".

export type SignalKind = "c2pa" | "metadata" | "invisible-watermark" | "novelai-alpha";

/**
 * - `ai`: claims/indicates the image was generated by an AI model.
 * - `edited`: composite / edited with AI (e.g. compositeWithTrainedAlgorithmicMedia, generative fill).
 * - `camera`: signed claim of a camera capture (C2PA digitalCapture).
 * - `unknown`: provenance present but says nothing about AI (e.g. a C2PA
 *   manifest from an editor with no AI actions).
 */
export type Verdict = "ai" | "edited" | "camera" | "unknown";

export interface ImageSignal {
  kind: SignalKind;
  verdict: Verdict;
  /** Signed AND the signer chains to the bundled C2PA Trust List AND validation passed. */
  trusted: boolean;
  /** Cryptographically signed (only C2PA; NovelAI's own signature is not verified). */
  signed: boolean;
  /** Short badge text, e.g. "CR", "AI claim", "SD watermark". */
  label: string;
  /** Human-readable explanation for the hover card / popup. */
  detail: string;
  /** Generator/provider if known, e.g. "OpenAI", "Stable Diffusion XL", "Midjourney". */
  provider?: string;
}

/** Structured C2PA summary (present when a manifest store was found). */
export interface C2paSummary {
  /** Signer certificate common name / organisation, if reported. */
  signer?: string;
  issuer?: string;
  signedAt?: string;
  /** Trusted = valid and chains to the bundled C2PA Trust List. */
  trusted: boolean;
  /** c2pa-rs validation state: "Trusted" | "Valid" | "Invalid". */
  validationState?: string;
  claimGenerator?: string;
  /** IPTC digital source type URIs found in c2pa.actions (short form, e.g. "trainedAlgorithmicMedia"). */
  digitalSourceTypes: string[];
  /** Action labels, e.g. ["c2pa.created", "c2pa.edited"]. */
  actions: string[];
  /** Software agents named in actions (e.g. "DALL·E", "Adobe Firefly"). */
  softwareAgents: string[];
  ingredientCount: number;
  /** Failure codes from validation (e.g. "assertion.dataHash.mismatch", "signingCredential.untrusted"). */
  failures: string[];
}

export type CheckState =
  | "found"
  | "not-found"
  | "skipped"
  | "error";

export interface ImageChecks {
  c2pa: CheckState;
  metadata: CheckState;
  /** "not-found" here means "not found (fragile)": it is not evidence of anything. */
  invisibleWatermark: CheckState;
  novelaiAlpha: CheckState;
}

export type ImageStatus =
  /** Analysed (signals may still be empty). */
  | "ok"
  /** The optional host permission for this image's origin is not granted. */
  | "permission-needed"
  /** settings.checkImages is off. */
  | "disabled"
  /** Could not fetch/decode (see errors). */
  | "error";

export interface ImageProvenanceResult {
  src: string;
  status: ImageStatus;
  /** Optional small preview (data: URL), e.g. from a C2PA manifest thumbnail. */
  thumbnail?: string;
  signals: ImageSignal[];
  checks: ImageChecks;
  c2pa?: C2paSummary;
  /** Detected container format ("jpeg", "png", "webp", ...). */
  format?: string;
  width?: number;
  height?: number;
  bytes?: number;
  /** Non-fatal notes, e.g. "invisible watermark: not found (fragile, not evidence)". */
  notes: string[];
  errors: string[];
}

// ---- Content -> background request shapes ----

/** One image candidate discovered on the page. */
export interface ImageCandidate {
  /** Absolute URL (http/https), or a synthetic id for data:/blob: images. */
  src: string;
  /** For data:/blob: images the content script reads bytes itself (base64). */
  bytesB64?: string;
  mime?: string;
  /** Displayed size (CSS px), for prioritisation only. */
  displayWidth?: number;
  displayHeight?: number;
}

export interface ProvenanceScanImagesRequest {
  images: ImageCandidate[];
}

export interface ProvenanceScanImagesResponse {
  results: ImageProvenanceResult[];
  /** True if settings.checkImages is off (results are empty). */
  disabled?: boolean;
  /** Origins (e.g. "https://cdn.example.com/*") that need the optional host permission. */
  permissionNeeded: string[];
}

/** Background -> provenance host (Chrome offscreen doc). */
export interface ProvenanceHostRequest {
  images: ImageCandidate[];
}

export interface ProvenanceHostResponse {
  results: ImageProvenanceResult[];
}

// ---- Text ----

export interface TextProvenanceResult {
  /** A C2PA text manifest wrapper (C2PATXT\0 in variation selectors) was found. */
  found: boolean;
  /** Offset/length (UTF-16 code units) of the wrapper in the scanned text. */
  offset?: number;
  length?: number;
  manifestBytes?: number;
  /** Structural issues from c2pa-text's validator. */
  issues: string[];
  /**
   * Signature verification status. "unverified" means only the wrapper was
   * detected and the manifest signature was not checked.
   */
  verification: "unverified" | "verified" | "failed";
  c2pa?: C2paSummary;
  detail: string;
}

export interface ProvenanceVerifyTextRequest {
  /** Base64 of the JUMBF manifest store extracted from the text. */
  manifestB64: string;
}

// ---- Static "cannot be checked locally" list ----

export interface UncheckableScheme {
  id: string;
  name: string;
  usedBy: string;
  media: string;
  why: string;
  /** Official checker, opened only on explicit user click (never automatic uploads). */
  checker?: { label: string; url: string };
}
